[package]
name = "cl-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cl-core = { path = "../cl-core", version = "0.1.0" }

anyhow = "1.0.75"
clap = { version = "4.4.1", features = ["derive"] }
dirs = "5.0.1"
itertools = "0.11.0"
log = "0.4.20"
owo-colors = "3.5.0"
regex = "1.9.4"
serde = { version = "1.0.188", features = ["derive"] }
strfmt = "0.2.4"
thiserror = "1.0.47"
