[package]
name = "cl"
version = "0.5.4"
edition = "2021"
homepage = "https://github.com/rvigo/cl"
repository = "https://github.com/rvigo/cl"
readme = "README.md"
description  = "Group your commands and aliases in an organized and human readable place" 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = { version = "0.19.0", features = ["crossterm"] }
crossterm = "0.25.0"
toml = "0.7.1"
anyhow = "1.0.68"
serde = { version = "1.0.152", features = ["derive"] }
dirs = "4.0.0"
itertools = "0.10.5"
unicode-width = "0.1"
clap = { version = "4.0.32", features = ["derive"] }
lazy_static = "1.4.0"
strfmt = "0.2.2"
owo-colors = "3.5.0"
tui-textarea = { version = "0.2.0", features = ["crossterm"] }
flexi_logger = "0.24.2"
log = "0.4.17"
regex="1.7.1"
