[package]
name = "cl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.18.0"
crossterm = "0.24.0"
toml = "0.5.9"
anyhow = "1.0.0"
serde = { version = "1.0.104", features = ["derive"] }
dirs = "4.0.0"
itertools = "0.10.3"
unicode-width = "0.1"
clap = { version = "3.1.17", features = ["color"] }
