#!/usr/bin/env zsh

cl-exec-widget() {
    TRAPWINCH() {
        [[ -o zle ]] && zle reset-prompt; zle -R
    }
    
    local -a cl=(cl misc -f)
    local fzf=(
        fzf \
        --no-multi \
        --ansi \
        --no-sort \
        --cycle \
        --reverse \
        --exit-0 \
        --height 40% \
        --header='Enter: set prompt with the selected command' \
        --bind='enter:abort+execute:echo cl exec {1q} $(if [[ ! -z {2q} ]] then  echo --namespace {2q} | sed "s/[()]//g"; fi)'\
        --preview='[[ ! -z {2q} ]] && echo "$(cl misc -d -a {1q} -n $(echo {2q} | sed "s/[()]//g";))" || echo "$(cl misc -d -a {1q})"' \
        --preview-window=right:60%:wrap 
    ) 

    local choice=$($cl | $fzf)
    if [[ ! -z "$choice" ]]; then
        zle -U "$choice"
        zle reset-prompt
    fi
}

if [[ -x "$(command -v fzf)" ]]; then
    zle -N cl-exec-widget
    bindkey ^o cl-exec-widget
fi
