[package]
name = "cl-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
dirs = "5.0.1"
itertools = "0.11.0"
log = "0.4.17"
serde = { version = "1.0.160", features = ["derive"] }
thiserror = "1.0.40"
toml = "0.7.3"
tracing = "0.1"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3"
