name: Test & Validations

on:
  push:
    branches:
      - "**"
jobs:
  format:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@1.67.0
        with:
          components: rustfmt
      - name: Check formatting
        run: |
          cargo fmt --all -- --check
  clippy:
    name: clippy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@1.67.0
        with:
          components: clippy
      - name: Check the lints
        run: |
          cargo clippy -- -D warnings
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@1.67.0
      - name: Unit Test
        run: |
          cargo test
        env:
          RUST_BACKTRACE: 1
